spring:
  application:
    name: SpringM10
  profiles:
    active: prod
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

logging:
  level:
    org.springframework.graphql: DEBUG
    org.hibernate: DEBUG
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: abbos2004postgresql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  task:
    execution:
      pool:
        core-size: 20
        max-size: 100
        keep-alive: 60s
        queue-capacity: 500
      thread-name-prefix: prod-