spring:
  application:
    name: SpringM10
  profiles:
    active: prod
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 2c931fe2fc5a6a
    password: b4b4f8dabf1183
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
app:
  log-mode: false
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: abbos2004postgresql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  task:
    execution:
      pool:
        core-size: 20
        max-size: 100
        keep-alive: 60s
        queue-capacity: 500
      thread-name-prefix: prod-
---
spring:
  config:
    activate:
      on-profile: test
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        keep-alive: 10s
        queue-capacity: 30
      thread-name-prefix: test-
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 9090