spring:
  application:
    name: SpringM10
  profiles:
    active: prod
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 2c931fe2fc5a6a
    password: b4b4f8dabf1183
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  shell:
    interactive:
      enabled: true
logging:
  level:
    root: error
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: abbos2004postgresql
  jpa:
    hibernate:
      ddl-auto: update
  task:
    execution:
      pool:
        core-size: 20
        max-size: 100
        keep-alive: 60s
        queue-capacity: 500
      thread-name-prefix: prod-
---